version: '3.7'

services:
    api:
        image: api:latest
        #command: sh -c "gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app --host 0.0.0.0 --port 3000"
        command: sh -c "uvicorn main:app --host 0.0.0.0 --port 3000"
        build:
            context: ./api
            dockerfile: Dockerfile
            network: host
            dns:
              - 8.8.8.8
            # args:
            #     HTTP_PROXY: http://xx.xx.xx.xx:xx
            #     HTTPS_PROXY: http://xx.xx.xx.xx:xx
        ports:
          - 3000:3000
        volumes:
          - ./html:/home/html
        depends_on:
        - front
    front:
        image: front:latest
        build:
            context: ./html
            dockerfile: Dockerfile
        ports:
          - 80:80
        volumes:
          - ./html:/home/html
      
