version: '3.10.5'

services:
    api:
        image: api:latest
        build:
            context: ./api
            dockerfile: Dockerfile
        ports:
          - 3000:3000
        volumes:
          - ./html:/home/html
        depends_on:
        - front

    front:
        image: front:latest
        build:
            context: ./html
            dockerfile: Dockerfile
        ports:
          - 80:80
        volumes:
          - ./html:/home/html
      
