version: '3.10.5'

services:
    front:
        image: front:latest
        build:
            context: ./html
            dockerfile: Dockerfile
        ports:
          - 80:80
        volumes:
          - ./html:/home/html
      
